### Root
GET http://localhost:8000/

### Get all recipes
GET http://localhost:8000/recipes

### Get recipe by valid ID
GET http://localhost:8000/recipes/1

### Get recipe by invalid ID (should fail - negative ID)
GET http://localhost:8000/recipes/-1

### Create a new recipe
POST http://localhost:8000/recipes
Content-Type: application/json

{
  "name": "Test Recipe",
  "description": "A test recipe",
  "fooditem_id": 1,
  "category_id": 1
}

### Update recipe by valid ID
PUT http://localhost:8000/recipes/1
Content-Type: application/json

{
  "name": "Updated Recipe Name",
  "fooditem_id": 1
}

### Update recipe by invalid ID (should fail - negative ID)
PUT http://localhost:8000/recipes/-1
Content-Type: application/json

{
  "name": "Should Fail",
  "fooditem_id": 1
}

### Delete recipe by valid ID
DELETE http://localhost:8000/recipes/1

### Delete recipe by invalid ID (should fail - negative ID)
DELETE http://localhost:8000/recipes/-1

### Get all ingredients
GET http://localhost:8000/ingredients

### Get ingredient by valid ID
GET http://localhost:8000/ingredients/1

### Get ingredient by invalid ID (should fail - negative ID)
GET http://localhost:8000/ingredients/-1

### Create a new ingredient
POST http://localhost:8000/ingredients
Content-Type: application/json

{
  "ingredient_name": "Test Salt"
}

### Update ingredient by valid ID
PUT http://localhost:8000/ingredients/1
Content-Type: application/json

{
  "ingredient_name": "Sea Salt"
}

### Update ingredient by invalid ID (should fail - negative ID)
PUT http://localhost:8000/ingredients/-1
Content-Type: application/json

{
  "name": "Should Fail"
}

### Delete ingredient by valid ID
DELETE http://localhost:8000/ingredients/1

### Delete ingredient by invalid ID (should fail - negative ID)
DELETE http://localhost:8000/ingredients/-1

### Get ingredients for a recipe by valid recipe ID
GET http://localhost:8000/recipes/1/ingredients

### Get ingredients for a recipe by invalid recipe ID (should fail - negative ID)
GET http://localhost:8000/recipes/-1/ingredients

### Add ingredient to recipe
POST http://localhost:8000/recipes/1/ingredients
Content-Type: application/json

{
  "ri_ingredient_id": 2,
  "ri_unit_type_id": 1,
  "ri_quantity": 1
}

### Update recipe ingredient by valid IDs
PUT http://localhost:8000/recipes/1/ingredients/2
Content-Type: application/json

{
  "ri_unit_type_id": 1,
  "ri_quantity": 2
}

### Update recipe ingredient by invalid IDs (should fail - negative IDs)
PUT http://localhost:8000/recipes/-1/ingredients/-2
Content-Type: application/json

{
  "ri_unit_type_id": 1,
  "ri_quantity": 2
}

### Remove ingredient from recipe by valid IDs
DELETE http://localhost:8000/recipes/1/ingredients/2

### Remove ingredient from recipe by invalid IDs (should fail - negative IDs)
DELETE http://localhost:8000/recipes/-1/ingredients/-2

### Get all categories
GET http://localhost:8000/categories

### Get category by valid ID
GET http://localhost:8000/categories/1

### Get category by invalid ID (should fail - negative ID)
GET http://localhost:8000/categories/-1

### Create a new category
POST http://localhost:8000/categories
Content-Type: application/json

{
  "category_name": "Dessert"
}

### Update category by valid ID
PUT http://localhost:8000/categories/1
Content-Type: application/json

{
  "category_name": "Updated Dessert"
}

### Update category by invalid ID (should fail - negative ID)
PUT http://localhost:8000/categories/-1
Content-Type: application/json

{
  "name": "Should Fail"
}

### Delete category by valid ID
DELETE http://localhost:8000/categories/1

### Delete category by invalid ID (should fail - negative ID)
DELETE http://localhost:8000/categories/-1

### Get all food items
GET http://localhost:8000/food-items

### Get food item by valid ID
GET http://localhost:8000/food-items/1

### Get food item by invalid ID (should fail - negative ID)
GET http://localhost:8000/food-items/-1

### Create a new food item
POST http://localhost:8000/food-items
Content-Type: application/json

{
  "fooditem_name": "Apple"
}

### Update food item by valid ID
PUT http://localhost:8000/food-items/1
Content-Type: application/json

{
  "fooditem_name": "Green Apple"
}

### Update food item by invalid ID (should fail - negative ID)
PUT http://localhost:8000/food-items/-1
Content-Type: application/json

{
  "fooditem_name": "Should Fail"
}

### Delete food item by valid ID
DELETE http://localhost:8000/food-items/1

### Delete food item by invalid ID (should fail - negative ID)
DELETE http://localhost:8000/food-items/-1

### Get all meals
GET http://localhost:8000/meals

### Get meal by valid ID
GET http://localhost:8000/meals/1

### Get meal by invalid ID (should fail - negative ID)
GET http://localhost:8000/meals/-1

### Create a new meal
POST http://localhost:8000/meals
Content-Type: application/json

{
  "meal_name": "Breakfast"
}

### Update meal by valid ID
PUT http://localhost:8000/meals/1
Content-Type: application/json

{
  "meal_name": "Brunch"
}

### Update meal by invalid ID (should fail - negative ID)
PUT http://localhost:8000/meals/-1
Content-Type: application/json

{
  "meal_name": "Should Faild"
}

### Delete meal by valid ID
DELETE http://localhost:8000/meals/1

### Delete meal by invalid ID (should fail - negative ID)
DELETE http://localhost:8000/meals/-1
